---
# Example default configuration for Library nodes (by group).

# If you want you can assume the managed hosts are wholly dedicated to
# serving content from the Calibre server. To ensure that the most
# resources are used for the library software, flag that we'll remove
# unnecessary pacakges in order to free up more disk space.
#
# See the `unnecessary_packages` variable for a list of package names
# that will be removed.
uninstall_unnecessary_packages: false

# Lists of packages deemed safe to remove, assuming a headless server
# is desired (i.e., `uninstall_unnecessary_packages` is `true`).
unnecessary_packages:
  # Package names that are the same regardless of the underlying OS.
  common:
    - "libreoffice*"
    - "tree"

    # Don't use a star glob for these, in case they're not installed.
    - "wolfram-engine"
    - "wolframscript"

  debian:
    - "alacarte"
    - "ant"
    - "aptitude*"
    - "asciidoc"
    - "aspell"
    - "at"
    - "autoconf"
    - "blt"
    - "bluealsa"
    - "bluej"
    - "bsd-mailx"
    - "bsdmainutils"
    - "cifs-utils"
    - "chromium*"
    - "claws-mail"
    - "coinor-libcbc3"
    - "coinor-libcgl1"
    - "coinor-libclp1"
    - "crda"
    - "cups-*"
    - "dblatex"
    - "debian-reference-en"
    - "desktop-base"
    - "desktop-file-utils"
    - "epiphany-browser"
    - "esound*"
    - "exim4*"
    - "galculator"
    - "gnome-*"
    - "greenfoot"
    - "gtk2*"
    - "jackd*"
    - "*javascript*"
    - "*lightdm*"
    - "lx*"
    - "*lxde*"
    - "openbox*"
    - "penguinspuzzle"
    - "pipanel"
    - "scratch"
    - "sonic-pi"
    - "xserver*"

  # TODO: List unnecessary packages on RedHat-based OS's.
  redhat:

# By default we'll assume that libraries should have security-hardened
# configurations. Set this to `false` if you prefer to skip hardening.
hardened_hosts: true

# When hardening hosts (with `hardened_hosts` set to `true`), we won't
# allow SSH connections from any user not in this specific user group.
sshd_allow_group: ssh-users

# Whether or not to install a Tor server and to provision any Onion
# services on the managed host.
tor_onion_service_server: true

# Define the Onion services you want available on the managed host.
# None of these will be added unless the `tor_onion_service_server`
# variable is `true`.
onion_services:

  # This Onion service is used primarily for NAT punching.
  - name: onion-ssh # The name of the Onion service directory.
    version: 2      # The Onion service protocol.
    virtports:      # The virtual port(s) to expose on the Onion.
      - port_number: 22        # The Onion's port number itself.
        target_addr: 127.0.0.1 # The target address of the service.
        target_port: 22        # The target port of the service.
    auth_type: stealth         # The Onion's authentication type. This
                               # can be `stealth`, `basic` or `false`.
    clients:        # A list of clients to authenticate.
      - admin

  # This Onion service makes the Calibre library available as an
  # authenticated stealth Onion service to "alice" and "bob".
  - name: onion-library
    version: 2
    virtports:
      - port_number: 80
        target_addr: 127.0.0.1
        target_port: 8080
    auth_type: stealth
    clients:
      - alice
      - bob

# Add the Calibre server user to these additional user groups.
calibre_server_user_groups:
  - ssh-users

calibre_libraries:
  - library_dir: "{{ calibre_server_home_dir }}/Neighborhood Library"
    listen_port: 8080
    sync_source: "~/Documents/Calibre Library/" # Trailing slash for "contents of."
