---
- name: Open ports in IPv4 firewall.
  when: open_ports is defined
  set_fact:
    ipv4_tables: >
      {{ ipv4_tables | combine({
          'filter': {
            'INPUT': {
              'rules': ipv4_tables.filter.INPUT.rules + [
                item | combine({
                  'target': 'ACCEPT'
                })
              ]
            }
          }
      }, recursive=True) }}
  loop: "{{ open_ports }}"

- name: Determine firewall configuration for Libraries.
  when: calibre_libraries is defined
  block:
    - name: Get configured Calibre listen ports.
      set_fact:
        calibre_ports: "{{ calibre_libraries | selectattr('listen_port', 'defined') | map(attribute='listen_port') | list }}"

    - name: Register Calibre ports with IPv4 firewall.
      set_fact:
        ipv4_tables: >
          {{ ipv4_tables | combine({
            'filter': {
              'INPUT': {
                'rules': ipv4_tables.filter.INPUT.rules + [{
                  'protocol': 'tcp',
                  'destination_port': item,
                  'target': 'ACCEPT'
                }]
              }
            }
          }, recursive=True) }}
      loop: "{{ calibre_ports }}"

    - name: Register Calibre ports with IPv6 firewall.
      set_fact:
        ipv6_tables: >
          {{ ipv6_tables | combine({
            'filter': {
              'INPUT': {
                'rules': ipv6_tables.filter.INPUT.rules + [{
                  'protocol': 'tcp',
                  'destination_port': item,
                  'target': 'ACCEPT'
                }]
              }
            }
          }, recursive=True) }}
      loop: "{{ calibre_ports }}"

- name: Determine firewall configuration for hosted Web sites.
  when:
    - web_landing_page_resources_dir is defined
    - lighttpd_config is defined
  block:
    - name: Get globally configured Web server port.
      set_fact:
        lighttpd_ports: >
          {{ lighttpd_config
          | selectattr('server', 'defined') | map(attribute='server')
          | selectattr('port', 'defined') | map(attribute='port')
          | list
          }}

    # TODO: Only works on first-level conditionals. It should recurse.
    - name: Get conditionally configured Web server port.
      set_fact:
        lighttpd_ports: >
          {{ lighttpd_ports + lighttpd_config
          | selectattr('conditional', 'defined') | map(attribute='conditional') | flatten(1)
          | selectattr('options', 'defined') | map(attribute='options') | flatten(1)
          | selectattr('server', 'defined') | map(attribute='server')
          | selectattr('port', 'defined') | map(attribute='port')
          | list
          }}

    - name: Register Lighttpd ports with IPv4 firewall.
      set_fact:
        ipv4_tables: >
          {{ ipv4_tables | combine({
            'filter': {
              'INPUT': {
                'rules': ipv4_tables.filter.INPUT.rules + [{
                  'protocol': 'tcp',
                  'destination_port': item,
                  'target': 'ACCEPT'
                }]
              }
            }
          }, recursive=True) }}
      loop: "{{ lighttpd_ports }}"

    - name: Register Lighttpd ports with IPv6 firewall.
      set_fact:
        ipv6_tables: >
          {{ ipv6_tables | combine({
            'filter': {
              'INPUT': {
                'rules': ipv6_tables.filter.INPUT.rules + [{
                  'protocol': 'tcp',
                  'destination_port': item,
                  'target': 'ACCEPT'
                }]
              }
            }
          }, recursive=True) }}
      loop: "{{ lighttpd_ports }}"
