---
# Hardening tasks common to all Operating Systems.

- name: Create SSH users group.
  group:
    name: "{{ sshd_allow_group }}"
    state: present
    system: yes

- name: Add Ansible user to SSH users group.
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: "{{ sshd_allow_group }}"

- name: Restrict SSH access to specific user group.
  # TODO: Eventually, templatize this for more control, as `sshd`
  #       stops applying options at the first directive found.
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowGroups "
    line: "AllowGroups {{ sshd_allow_group }}"
    state: present

- name: Apply hardened SSH configuration.
  service:
    name: ssh
    state: reloaded
  changed_when: false

- name: Include OS-specific hardening tasks.
  when: ansible_os_family is defined
  include_tasks: "harden-{{ ansible_os_family | default('Debian') | lower }}.yml"
