---
- name: Provision Library nodes with Dark Web access if requested.
  hosts: all
  become: true

  pre_tasks:
    - name: Register firewall configuration.
      import_tasks: tasks/configure-firewall.yaml

  roles:
    - common
    - calibre
    - lighttpd

    # Run the Tor role for a Tor server that's NOT also an OnionShare
    # receiver; OnionShare receiving servers enact Tor automatically.
    - role: tor
      when:
        - tor_onion_service_server | default(false)
        - not onionshare_receiver_mode | default(false)

    # The OnionShare role will run the Tor role.
    - role: onionshare
      when:
        - tor_onion_service_server | default(false)
        - onionshare_receiver_mode | default(false)

  tasks:
    - name: Install Calibre Content server resources.
      when: calibre_server_resources_files is defined
      copy:
        src: "{{ calibre_server_resources_files }}/content_server"
        dest: "{{ calibre_server_home_dir }}/.config/calibre/resources/"
        owner: "{{ calibre_server_username }}"
      notify: Restart Calibre.

    - name: Create Web landing page.
      when: web_landing_page_resources_dir is defined
      block:
        - name: Install Web landing page files.
          ignore_errors: true # It's possible we have no files to copy. :)
          synchronize:
            src: "files/{{ web_landing_page_resources_dir }}/"
            dest: /var/www/html/
            rsync_opts:
              - "--exclude=.git"
              - "--chown={{ lighttpd_server_username }}:{{ lighttpd_server_username }}"
              - "--chmod=D555,F444"
          # FIXME: Why does the `rsync` command always return changed?
          changed_when: false

        - name: Ensure Web landing page directory structure exists.
          when: item.state == "directory"
          file:
            path: "/var/www/html/{{ item.path }}"
            state: directory
            owner: "{{ lighttpd_server_username }}"
            group: "{{ lighttpd_server_username }}"
            mode: "555"
          with_filetree: "templates/{{ web_landing_page_resources_dir }}"

        - name: Write Web landing page templates.
          when: item.state == "file"
          template:
            src: "{{ item.src }}"
            dest: "/var/www/html/{{ item.path }}"
            owner: "{{ lighttpd_server_username }}"
            group: "{{ lighttpd_server_username }}"
            mode: "444"
          with_filetree: "templates/{{ web_landing_page_resources_dir }}"
